### ISSUE TITLE
remove mention of the proprietary windows operating system

### ISSUE THREAD

**Issue by RodrigoDornelles** [psywave-games/tedious-game#8]
* **English translation has the following quotes in a book**

| constant identifier | translation text | 
| ---------------------------- | :----------------------------------------------------------------------- | 
| `msg.interact_book0` | I do feel some sympathy for people who use Windows |
| `msg.interact_book1` | especially those who've been using it for a long time. |
| `msg.interact_book2` | There were a lot of bugs in Windows 3.x |
| `msg.interact_book3` | Windows 95 |
| `msg.interact_book4` | Windows 98 |
| `msg.interact_book5` | Windows 98SE |
| `msg.interact_book6` | Windows 2000 |
| `msg.interact_book7` | Windows ME |
| `msg.interact_book8` | Windows XP |
| `msg.interact_book9` | Windows Vista |
| `msg.interact_book10` | and even in Windows 7, Windows 8 and Windows 8.1 |
| `msg.interact_book11` | That's why we're going all-out with Windows 10, |
| `msg.interact_book12` | to get rid of those bugs and replace them with all-new ones. |

| gameplay screenshot |
| ---------------------------- |
| ![gameplay_screenshot](https://cdn.discordapp.com/attachments/694175007366053918/748600264243675256/unknown.png) |

**Comment by marcusmmmz** [comment]
Yeah Yeah relatable 100 mate yeah definitely of course go for it
